{% set name = "graylint" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graylint-{{ version }}.tar.gz
  sha256: b7e0eab6c159684dbf5ef84e942c3340f6a6549b02a3d11b1a1763cc4f8f0593

build:
  entry_points:
    - graylint = graylint.__main__:main_with_error_handling
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - darkgraylib >=1.2.0,<1.3.dev0

test:
  imports:
    - graylint
  commands:
    - pip check
    - graylint --help
  requires:
    - pip

about:
  home: https://github.com/akaihola/graylint
  summary: Run linters and show only new errors compared to an older commit
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - akaihola
