{% set name = "graylint" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graylint-{{ version }}.tar.gz
  sha256: 72ad3357298fb6627b383547cdf9a08d544d9a67cc4b4eced99bc23eff2a8561

build:
  entry_points:
    - graylint = graylint.__main__:main_with_error_handling
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - darkgraylib >=1.3.1,<1.4.dev0

test:
  imports:
    - graylint
  commands:
    - pip check
    - graylint --help
  requires:
    - pip

about:
  home: https://github.com/akaihola/graylint
  summary: Run linters and show only new errors compared to an older commit
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - akaihola
